// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa9IYkc7iJWWCV6cp1OMtEUvOtVGkOVxo',
    appId: '1:718586716164:web:62633b3397d20834d25551',
    messagingSenderId: '718586716164',
    projectId: 'taskeen-6d781',
    authDomain: 'taskeen-6d781.firebaseapp.com',
    storageBucket: 'taskeen-6d781.appspot.com',
    measurementId: 'G-M5R2YB91XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6bfn6hNzJFdVVjU1G6i11on268nSvHuw',
    appId: '1:718586716164:android:13f7532707680bd4d25551',
    messagingSenderId: '718586716164',
    projectId: 'taskeen-6d781',
    storageBucket: 'taskeen-6d781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtiNXdi8MlifJLrh2mFzmqaB2c-jcbZqU',
    appId: '1:718586716164:ios:8a24328880839768d25551',
    messagingSenderId: '718586716164',
    projectId: 'taskeen-6d781',
    storageBucket: 'taskeen-6d781.appspot.com',
    iosClientId: '718586716164-nac0826sdpcp70pp2kdop5dkpog9m141.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskeen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtiNXdi8MlifJLrh2mFzmqaB2c-jcbZqU',
    appId: '1:718586716164:ios:8a24328880839768d25551',
    messagingSenderId: '718586716164',
    projectId: 'taskeen-6d781',
    storageBucket: 'taskeen-6d781.appspot.com',
    iosClientId: '718586716164-nac0826sdpcp70pp2kdop5dkpog9m141.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskeen',
  );
}
